**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/group-by-having-count).**

---

# Introduction

Queries with **GROUP BY** can be powerful. There are many small things that can trip you up (like the order of the clauses), but it will start to feel natural once you've done it a few times. Here, you'll write queries using **GROUP BY** to answer questions from the Hacker News dataset.

Before you get started, run the following cell to set everything up:

In [1]:
# Set up feedback system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex3 import *
print("Setup Complete")

Using Kaggle's public dataset BigQuery integration.
Setup Complete

The code cell below fetches the `full` table from the `hacker_news` dataset.  We also preview the first five rows of the table.

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "hacker_news" dataset
dataset_ref = client.dataset("hacker_news", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Construct a reference to the "full" table
table_ref = dataset_ref.table("full")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five lines of the table
client.list_rows(table, max_results=5).to_dataframe()

Using Kaggle's public dataset BigQuery integration.

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,None,None,None,None,None,NaN,1555343704,2019-04-15 15:55:04+00:00,story,19666203,NaN,NaN,NaN,True
1,None,None,None,None,None,NaN,1555346357,2019-04-15 16:39:17+00:00,story,19666640,NaN,NaN,NaN,True
2,None,None,None,None,None,NaN,1555348836,2019-04-15 17:20:36+00:00,story,19666968,NaN,NaN,NaN,True
3,None,None,None,None,None,NaN,1556166014,2019-04-25 04:20:14+00:00,story,19667009,NaN,NaN,NaN,True
4,None,None,None,True,None,NaN,1555349468,2019-04-15 17:31:08+00:00,story,19667053,NaN,NaN,NaN,True

# Exercises

### 1) Prolific commenters

Hacker News would like to send awards to everyone who has written more than 10,000 posts. Write a query that returns all authors with more than 10,000 posts as well as their post counts. Call the column with post counts `NumPosts`.

In case sample query is helpful, here is a query you saw in the tutorial to answer a similar question:
```
query = """
        SELECT parent, COUNT(1) AS NumPosts
        FROM `bigquery-public-data.hacker_news.full`
        GROUP BY parent
        HAVING COUNT(1) > 10
        """
```

In [11]:
# 글을 10000개 이상 작성한 작성자와 글 개수를 가져오는 
# Query to select prolific commenters and post counts
prolific_commenters_query = """
                            SELECT `by` AS author, COUNT(1) AS NumPosts
                            FROM `bigquery-public-data.hacker_news.full`
                            GROUP BY author
                            HAVING COUNT(1) > 10000
                            """
# COUNT(1)은 각 작성자가 작성한 글의 수를 계산하는 집계 함수
# COUNT(1)은 각 그룹 내에서 행의 수를 세는 함수
# (by)가 작성한 게시물 수를 세기 위해 사용
# GROUP BY by는 by 열을 기준으로 결과를 그룹화. 즉, 각 사용자별로 행이 그룹화

# prolific_commenters_query = """
#                         SELECT by ,COUNT(1)
#                         FROM `bigquery-public-data.hacker_news.full`
#                         GROUP BY by 
#                         HAVING COUNT(1) > 10000
    
# """
# by 열을 Author로 이름을 변경

# Set up the query (cancel the query if it would use too much of 
# your quota, with the limit set to 1 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)
query_job = client.query(prolific_commenters_query, job_config=safe_config)

# API request - run the query, and return a pandas DataFrame
prolific_commenters = query_job.to_dataframe()

# View top few rows of results
print(prolific_commenters.head())

# Check your answer
q_1.check()

         author  NumPosts
0        baddox     10342
1      tracker1     10047
2    imtringued     13603
3         sp332     20213
4  steveklabnik     17730

Correct

For the solution, uncomment the line below.

In [14]:
q_1.solution()

Solution:
```python

prolific_commenters_query = """
                            SELECT `by` AS author, COUNT(1) AS NumPosts
                            FROM `bigquery-public-data.hacker_news.full`
                            GROUP BY author
                            HAVING COUNT(1) > 10000
                            """

```

### 2) Deleted comments

How many comments have been deleted? (If a comment was deleted, the `deleted` column in the table will have the value `True`.)

In [22]:
# Write your query here and figure out the answer
Deleted_comments_query = '''
                        SELECT COUNT(1)
                        FROM `bigquery-public-data.hacker_news.full`
                        WHERE deleted = True
                        '''
# 쿼리 실행
query_job = client.query(Deleted_comments_query)
# 결과
query_job.to_dataframe()

       f0_
0  1187778

In [21]:
num_deleted_posts = 1187778 # Put your answer here

# Check your answer
q_2.check()

Correct

For the solution, uncomment the line below.

In [17]:
q_2.solution()

Solution:
```python

# Query to determine how many posts were deleted
deleted_posts_query = """
                      SELECT COUNT(1) AS num_deleted_posts
                      FROM `bigquery-public-data.hacker_news.full`
                      WHERE deleted = True
                      """

# Set up the query
query_job = client.query(deleted_posts_query)

# API request - run the query, and return a pandas DataFrame
deleted_posts = query_job.to_dataframe()

# View results
print(deleted_posts)

num_deleted_posts = 1187778

```

# Keep Going
**[Click here](https://www.kaggle.com/dansbecker/order-by)** to move on and learn about the **ORDER BY** clause.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*